### ISSUE TITLE
Update the final project plan

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#163]
Update the project libre file for the last time. Make sure to prioritize the tasks and show the progress and final plans as realistically as possible. 

* [x] Go over the issues and meeting notes to see who is supposed to do what
* [x] Update the plan in details
* [x] Update the long-term planning page in wiki

Deadline: 12.05.2024
Estimated effort: 2 hrs
Reviewer: @Mutti499

**Comment by kristinatrajkovski** [comment]
Completed. The result can be seen [here](https://github.com/bounswe/bounswe2024group9/wiki/Long%E2%80%90term-planning-%F0%9F%93%85). 

@Mutti499 can you please take a look?

**Comment by Mutti499** [comment]
I am on it !

**Comment by Mutti499** [comment]
I think it looks cool mate! Way to go
