### ISSUE TITLE
[Kristina] Correct Issues from Milestone 1

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#301]
According to the assistant's notes from milestone 1, the long term plan was not detailed enough, the glossary was missing and the design diagrams needed work done. Until the milestone 2, it shall be updated with all the issues and necessary work done.

- [x]  Make the long-term plan in Project Libre detailed with issues and assigned people
- [x] Add a glossary
- [x]  Add constructors to class diagrams
- [x] Remove include and extend from use-case diagrams
- [x] Sequence - communicate with objects

Make sure to commit it to the repo, the last time a link was given which essentially downloads the pdf representation. Instead, screenshots and the file itself should be found in repo and wiki.

Deadline: 29.11.2024 8:00
Estimated effort: 2hrs
Reviewer: @ceylingebes

**Comment by kristinatrajkovski** [comment]
I have completed the tasks. @ceylingebes you may check the status at [design diagrams](https://github.com/bounswe/bounswe2024group9/wiki/451-%E2%80%90-Design-Diagrams), [glossary](https://github.com/bounswe/bounswe2024group9/wiki/Glossary-%E2%80%90-451) and [long term plan](https://github.com/bounswe/bounswe2024group9/wiki/Long%E2%80%90term-planning-451)

**Comment by ceylingebes** [comment]
All the design diagrams, glossary and the long term plan looks okay to me. Thank you for your time, Kristina <3
